//GFX.h
#ifndef GUNTHRALLGFX
#define GUNTHRALLGFX

#include "font.h"
#include "palette.h"
#include "player1.h"
#include "playership_pal.h"
#include "pbullet1.h"
#include "asteroid.h"
#include "asteroid_palette.h"
#include "slime1_sheet.h"
#include "slime1_palette.h"
#include "phaes1_rows.h"
//#include "phaes1_hairb.h"
//#include "phaes1_hairc.h"
#include "phaes1_palette.h"
//#include "stage1_bga.h"
#include "stage1_bga_b.h"
#include "stage1_bga_b_map.h"
//#include "lvlstrip.h"
//#include "lvlstrip_map.h"
//#include "stage1_palette.h"
#include "level1_bga_palette.h"
#include "stage1_palette.h"
#include "stage1_bottombg.h"
#include "moons.h"
#include "sun.h"
#include "enemy_palette1.h"
#include "hitbox.h"
#include "enemy1.h"
#include "enemy2.h"
#include "enemy3.h"
#include "led_green.h"

#endif